#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba, with local mods

require "fileutils"

home = File.expand_path "~"

Dir["*"].each do | file |
  next if %w( bin install README.md ).include?(file)

  target = File.join(home, ".#{file}")
  if File.exists?(target) && !File.symlink?(target)
    FileUtils.cp target, "#{target}.saved"
  end

  FileUtils.ln_s File.expand_path(file), target, force: true
end
