#!/bin/bash
# environment variables used by everything

export EDITOR=vi
if [[ -e $HOME/bin/mate ]]; then
  export EDITOR="mate -w"
fi
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LESS="--hilite-search --tabs=4 -R"
export RSYNC_RSH=ssh

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/X11R6/bin
export MANPATH=$HOME/man:/usr/local/share/man:/usr/share/man:/usr/local/man
export INFOPATH=/usr/share/info
