#!/bin/bash
# environment variables used by everything

export EDITOR=vi
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LESS="--hilite-search --tabs=4"
export RSYNC_RSH=ssh
