#!/bin/bash
# environment variables for Homebrew

if command -v brew > /dev/null; then
  GNUBIN="$(brew --prefix coreutils)/libexec/gnubin"
  if [[ -d $GNUBIN ]]; then
    path_prepend PATH $GNUBIN
  fi
  GNUMAN="$(brew --prefix coreutils)/libexec/gnuman"
  if [[ -d $GNUMAN ]]; then
    path_prepend MANPATH $GNUMAN
  fi
fi
