#!/bin/bash
# environment variables for Homebrew

if command -v brew > /dev/null; then
  GNUBIN="$(brew --prefix coreutils)/libexec/gnubin"
  [[ -d $GNUBIN ]] && path_prepend PATH $GNUBIN

  GNUMAN="$(brew --prefix coreutils)/libexec/gnuman"
  [[ -d $GNUMAN ]] && path_prepend MANPATH $GNUMAN

  prefix_imagemagick="$(brew --prefix imagemagick@6)/lib/pkgconfig"
  [[ -d $prefix_imagemagick ]] && path_append PKG_CONFIG_PATH $prefix_imagemagick
fi
