#!/bin/bash
# environment variables for Homebrew

if command -v brew > /dev/null; then
  GNUBIN="$(brew --prefix coreutils)/libexec/gnubin"
  if [[ -d $GNUBIN ]]; then
    path_prepend PATH $GNUBIN
  fi
  GNUMAN="$(brew --prefix coreutils)/libexec/gnuman"
  if [[ -d $GNUMAN ]]; then
    path_prepend MANPATH $GNUMAN
  fi
fi

prefix_imagemagick="$(brew --prefix imagemagick@6)/lib/pkgconfig"
if [[ -d $prefix_imagemagick ]]; then
  path_append PKG_CONFIG_PATH $prefix_imagemagick
fi
