#!/bin/bash
# environment variables for PostgreSQL

# export PGHOST=localhost
if [[ -d /Applications/Postgres.app ]]; then
  export POSTGRES_HOME=/Applications/Postgres.app/Contents/MacOS
elif [[ -e /usr/local/bin/postgres ]]; then
  export POSTGRES_HOME=/usr/local
elif [[ -e /usr/local/pgsql/bin/postgres ]]; then
  export POSTGRES_HOME=/usr/local/pgsql
fi

[[ -n "$POSTGRES_HOME" ]] && [[ -d $POSTGRES_HOME/bin ]] && path_prepend PATH $POSTGRES_HOME/bin
