#!/bin/bash
# environment variables for PostgreSQL

# export PGHOST=localhost
if [[ -d /Applications/Postgres.app ]]; then
  export POSTGRES_HOME=/Applications/Postgres.app/Contents/MacOS
elif [[ -e /usr/local/bin/postgres ]]; then
  export POSTGRES_HOME=/usr/local
elif [[ -e /usr/local/pgsql/bin/postgres ]]; then
  export POSTGRES_HOME=/usr/local/pgsql
fi

if [[ -n "$POSTGRES_HOME" ]]; then
  if [[ -d $POSTGRES_HOME/bin ]]; then
    export PATH=$POSTGRES_HOME/bin:$PATH
  fi
fi
