#!/bin/bash
# asdf-vm/asdf

if [[ -f "$HOME/.asdf/asdf.sh" ]]; then
  source $HOME/.asdf/asdf.sh
fi
if [[ -f "$HOME/.asdf/completions/asdf.bash" ]]; then
  source $HOME/.asdf/completions/asdf.bash
fi
