#!/bin/bash
# setup for Java development

if [[ -d /System/Library/Java/JavaVirtualMachines/1.6.0.jdk ]]; then
	export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
	# export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.7.0u.jdk/Contents/Home
  export JAVA_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
fi

if [[ -n "$JAVA_HOME" ]]; then
  if [[ -d $JAVA_HOME/bin ]]; then
    export PATH=$JAVA_HOME/bin:$PATH
  fi
fi
