#!/bin/bash
# paths for Amazon Web Services (AWS)

if [[ -d "$HOME/ec2" ]]; then
  export EC2_HOME="$HOME/ec2"
  export EC2_PRIVATE_HOME="$HOME/.ec2"
fi

[[ -n "$EC2_HOME" ]] && [[ -d $EC2_HOME/bin ]] && path_prepend PATH $EC2_HOME/bin
