#!/bin/bash
# paths for Google Cloud

if [ -f "$HOME/Projects/google-cloud-sdk/path.bash.inc" ]; then source "$HOME/Projects/google-cloud-sdk/path.bash.inc"; fi
if [ -f "$HOME/Projects/google-cloud-sdk/completion.bash.inc" ]; then source "$HOME/Projects/google-cloud-sdk/completion.bash.inc"; fi
