#!/bin/bash
# paths

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/X11R6/bin
MANPATH=$HOME/man:/usr/local/share/man:/usr/share/man:/usr/local/man
INFOPATH=/usr/share/info

if [[ `type -path brew` ]]; then
  GNUBIN="$(brew --prefix coreutils)/libexec/gnubin"
  if [[ -d $GNUBIN ]]; then
    PATH="$GNUBIN:$PATH"
  fi
  GNUMAN="$(brew --prefix coreutils)/libexec/gnuman"
  if [[ -d $GNUMAN ]]; then
    MANPATH="$GNUMAN:$MANPATH"
  fi
fi

export PATH
export MANPATH
export INFOPATH