#!/bin/bash
# paths

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/X11R6/bin
export MANPATH=$HOME/man:/usr/local/share/man:/usr/share/man:/usr/local/man
export INFOPATH=/usr/share/info
