#!/bin/bash
# setup for Ruby

# export RUBYLIB=$HOME/lib/ruby

# export GEMDIR=`gem env gemdir`
gemdir() {
    `gem env gemdir`
}

gemdoc() {
    GEMDIR=$(gemdir)
    open $GEMDIR/doc/`$(which ls) $GEMDIR/doc | grep $1 | sort | tail -1`/rdoc/index.html
}

_gemdocomplete() {
    GEMDIR=$(gemdir)
    COMPREPLY=($(compgen -W '$(`which ls` $GEMDIR/doc)' -- ${COMP_WORDS[COMP_CWORD]}))
    return 0
}
complete -o default -o nospace -F _gemdocomplete gemdoc
