#!/bin/bash
# aliases

# aliases for GNU utilities, which Macports prefixes with "g"
if [[ -n `which gdu` ]]; then alias du='gdu'; fi
if [[ -n `which gfind` ]]; then alias find='gfind'; fi
if [[ -n `which gls` ]]; then alias ls='gls --color=auto'; fi
if [[ -n `which gmd5sum` ]]; then alias md5sum='gmd5sum'; fi

# EOL corrections -- Mac (<CR>,\r); Unix (<LF>,\n); Win (<CRLF>,\r\n)
alias mac2unix="perl -pi -e 's/\r/\n/g'"
alias unix2mac="perl -pi -e 's/\n/\r/g'"
alias win2unix="perl -pi -e 's/\r\n/\n/g'"
alias unix2win="perl -pi -e 's/\n/\r\n/g'"
alias win2mac="perl -pi -e 's/\r\n/\r/g'"
alias mac2win="perl -pi -e 's/\r/\r\n/g'"

# other aliases
# alias gitprep='find . \( -type d -empty \) -and \( -not -regex ./\.git.* \) -exec touch {}/.gitignore \;'
alias grep="grep --color=auto"
alias netlisten="netstat -naf inet | grep LISTEN"
alias psgrep="ps axwww | grep"
alias top="top -F -R -o cpu -s 2"