#!/bin/bash
# bash tab completion support

[[ -f /etc/bash_completion ]] && source /etc/bash_completion
[[ -f $HOME/.bash_completion ]] && source $HOME/.bash_completion

# load individual config files
if [[ -d ~/.bash_completion.d ]]; then
  for file in $(/bin/ls ~/.bash_completion.d/S*); do
    # echo "loading $file"
    source "$file"
  done
fi

# load private config files
# if [[ -d ~/.bash_completion.d-private ]]; then
#   for file in $(/bin/ls ~/.bash_completion.d-private/S*); do
#     # echo "loading $file"
#     source "$file"
#   done
# fi
